default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_DEV_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>_development

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>_production
  password: <%= ENV['POSTGRES_PROD_PASSWORD'] %>
